steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
options:
  serviceAccount: 'ci-cd-build@fine-method-448913-b8.iam.gserviceaccount.com' # Remplacez par votre compte de service
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET